AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'

inherit_mode:
  merge:
    - Exclude

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Layout/LineLength:
  Max: 170

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/GlobalVars:
  Exclude:
    - 'spec/**/*'
