AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'bin/**/*'
    - 'Guardfile'

inherit_mode:
  merge:
    - Exclude

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/LineLength:
  Max: 170
