AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'Guardfile'

inherit_mode:
  merge:
    - Exclude

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  Max: 170

Gemspec/RequireMFA:
  Enabled: false
