AllCops:
  Exclude:
    - 'bin/**/*'

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Semicolon:
  Enabled: false

Metrics/LineLength:
  Max: 170

Gemspec/RequiredRubyVersion:
  Enabled: false
