---
sudo: false
language: ruby
cache: bundler
before_install: gem install bundler

rvm:
  - 2.4.0
  - 2.5.3
  - 2.6.0
  - 2.6.1
  - 2.7.4
  - 3.0.0
  - 3.1.0

script:
  - bundle exec rubocop -DP
  - bundle exec rspec
