---
sudo: false
language: ruby
cache: bundler
before_install: gem install bundler

rvm:
  - 2.4.0
  - 2.5.3
#  - 2.6.0-preview3 travis does not support it yet

script:
  - bundle exec rubocop -DP
  - bundle exec rspec
